### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kamilzasada** [zkamil/ramlo#2]
- [ ] try to reduce time for generating documentation from RAML file
- [ ] rewrite code using ES2015 + Babel
- [ ] prepare website describing how to use ramlo - simple website like [API Workbench](http://apiworkbench.com/)
- [ ] create a logo for ramlo
- [ ] prepare a series of articles describing how API First approach can improve quality of the RESTful API implementation

**Comment by sichvoge** [comment]
@kamilzasada what is the expected ETA?

**Comment by kamilzasada** [comment]
@sichvoge probably around end of August

**Comment by sichvoge** [comment]
Awesome! Let me know if you want some PR. I will watch to the end of August for any updates ;)

BTW, would you be interested in a featured ["Sneak Peek"](http://forums.raml.org/c/sneak-peek) around your tool? Its a new section that I want to use to present interesting projects to the community.

**Comment by ulaBLUE** [comment]
Hi,
is this project not active anymore ?

**Comment by kamilzasada** [comment]
@ulaBLUE because of personal matters I don't have time now to actively develop the project, but I plan to get back to it soon.

**Comment by ulaBLUE** [comment]
Thank you for the clarification.
