### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by kamilzasada** [zkamil/ramlo#7]
### General
- [ ] Check if documentation presented in console after command `ramlo --help` is complete.
- [ ] Parse only files with extension *.raml and show error if a file is not a RAML 0.8 or 1.0.
- [x] Check if _ramlo_ can be installed locally in a project's node_module directory.
- [ ] Install _ramlo_ on different version of Node.js - at least v4.4.5 LTS and v6.2.0 Current
- [ ] Check if schemas defined at the root-level of the RAML file and included from external files are properly treated by RAML parser.
- [ ] Write unit tests.
### Code structure & layout
- [ ] Improve layout of generated documentation. @kamilzasada
- [ ] Refactor Jade template - use partials for repeated templates (for example tables with query parameters, schemas, etc.). @kamilzasada
- [ ] Try to split JavaScript code into modules. @kamilzasada
### Basic Information
- [ ] Present title of the API in the header (required).
- [ ] Present description of the API in the header (optional - new in RAML 1.0).
- [ ] Present URI of the API below title if defined (optional).
- [ ] Present API version at the end of the title or if `baseUri` has a `version` URI parameter, replace it and version should be presented as a part of API URI (optional).
- [x] Take care of `baseUriParameters` (optional).  
- [ ] Present available API protocols on the left side of API URI as `<span class="label">` (optional).
- [ ] Take care of `uriParameters` used inside `baseUri` parameter (optional).
### Named Parameters
- [ ] Named parameters are used for describing resource's methods, headers, response's schemas, etc. Basically in generated documentation they can be found in tables describing methods, headers, responses. (all parameters are optional). @kamilzasada
### User Documentation
- [ ] Show user documentation added to RAML file using `documentation` property at the beginning of the middle column documentation. Documentation can be written using Markdown. It can have `title` and `content` (optional).
### Resources
- [ ] Present top-level resources in the left menu and in the main documentation content. Resource name should be a header of the list of available methods. Resource name can be defined using `displayName` property or if not, it should be generated from resource's URI (required).
- [ ] Take care of `description` property which can be used for describing resource. Description should be presented only in the middle section of documentation - below resource's name (optional).
- [ ] Present resource's URI parameters in the table with columns: name, type, description. This is the same table as is used for displaying query parameters and API responses schemas. Values from `enum` parameter should be presented in the column with description (optional).
### Methods
- [ ] Present HTTP methods that can be performed on a resource and sub-resources in the left menu and also in the main content of the documentation. Each method can have `description` which can be written in Markdown (optional).
- [ ] Take care API's methods headers (optional).
- [ ] Take care API's methods query parameters, for example GET methods (optional).
- [ ] Take care API's methods body, or example POST methods (optional).
### Methods' responses
- [ ] Present multiple method's responses using tabs component. Response can have `schema` and `example` defined.
- [ ] Check if RAML parser does not have problems with including schemas and examples from external files.
- [ ] Take care of responses' headers (optional).
- [ ] Handle JSON Schemas with type 'array'.
- [ ] Handle nested JSON Schemas.

---
-  NOTE: All data for missing features can be gathered calling .toJSON() either in the root api or in other functions, then we can combine/parse easily on the template
#### Data Types
- Tested with type object, array, string, tables on jade are now dynamic.
- To test if examples are correctly
### Traits
- Tested and working as they should
### Resource Type
- On simple structures works correctly with the existing code, to be tested with complex structures
### Security Schemas
- tested with oauth2.0, oauth1.0 and basic.  Schemes are listed in the bottom of the page
- To Do:  link securedBy in endpoints to schemes
### RAML 1.0 Annotations
- To be implemented

**Comment by marinmetohu** [comment]
i'm taking care of 'baseUriParameters'

**Comment by marinmetohu** [comment]
added baseUriParameters below the Title, i'm not sure if it should be position there & the styling I guess must be improved

**Comment by wgrabowski** [comment]
I'll check this: "Check if ramlo can be installed locally in a project's node_module directory."

**Comment by sichvoge** [comment]
Hi, wow this is awesome! Let me know if you need any help to understand couple of things or need something from the js parser. We can also bring you up on the projects page if you finished, and I am also planning to give you a shout on twitter. But obviously only if you want me too :)

Is there any updated list where you are etc.?

**Comment by kamilzasada** [comment]
@sichvoge I've send you an email. Let's stay in touch :-)
